###
GET http://localhost:9000/api HTTP/1.1

###
PUT http://localhost:9000/api/2 HTTP/1.1
Content-Type: application/json

# {
#     "nom_alum": "Carlos Alberto"

# }

###
PUT http://localhost:9000/api2/1 HTTP/1.1
Content-Type: application/json

# {
#     "promedio": 9
# }

###
DELETE http://localhost:9000/api/2 HTTP/1.1

###
DELETE http://localhost:9000/api2/1 HTTP/1.1









 
